export { default as SignUp } from "./SignUp";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Home } from "./Home";
export { default as App } from "./menu-maker";
export { default as HomeUser } from "./HomeUser";
export { default as Categories} from "./categories-maker";
export { default as PaymentsHome } from "./PaymentsHome";
export { default as FeedbackHome } from "./FeedbackHome";
export { default as Courses } from "./course-maker";
